const https = require('https');
const fs = require('fs');
const path = require('path');

const fetchText = (url) => new Promise((resolve, reject) => {
    https.get(url, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => resolve(data));
    }).on('error', reject);
});

async function build() {
    try {
        console.log('Downloading 10000 frequent English words...');
        const text = await fetchText('https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-no-swears.txt');

        let words = text.split('\n')
            .map(w => w.trim().toLowerCase())
            .filter(w => w.length > 1 && /^[a-z]+$/.test(w));

        // Deduplicate just in case
        words = [...new Set(words)];

        // Typical vocabulary sizing:
        // Primary: ~800 words
        // Middle School: ~1600 words (+800)
        // High School: ~3500 words (+1900)
        // CET4: ~4500 words (+1000)
        // CET6: ~6000 words (+1500)
        // Mastered: All of them (or we just use logic: level='cet6' includes all before it)

        const levels = {
            primary: words.slice(0, 800),
            middle: words.slice(800, 1600),
            high: words.slice(1600, 3500),
            cet4: words.slice(3500, 4500),
            cet6: words.slice(4500, 6000)
        };

        const outputJs = `// Auto-generated by build_word_levels.js
const WordLevels = ${JSON.stringify(levels)};

// Export for module/browser hybrid use
if (typeof module !== 'undefined' && module.exports) {
    module.exports = WordLevels;
} else {
    window.WordLevels = WordLevels;
}
`;

        const outPath = path.join(__dirname, '..', 'lib', 'wordlevels.js');
        fs.writeFileSync(outPath, outputJs);
        console.log('Saved to', outPath);
    } catch (e) {
        console.error('Error:', e);
    }
}

build();
